import { invoiceRepository } from '@/repositories/invoice.repository';
import { generateInvoiceNumber } from '@/services/weddingWorkspace.service';
import { prisma } from '@/lib/prisma';
import { NotFoundError, InvalidTransitionError } from '@/lib/errors';
import type { Prisma } from '@/generated/prisma/client';

export interface InvoiceItemInput {
  description: string;
  vendorName?: string;
  amount: number;
  quantity?: number;
}

export interface InvoiceCreateData {
  clientName: string;
  clientPhone: string;
  clientEmail?: string;
  clientCity?: string;
  eventDate?: string;
  eventType?: string;
  subtotal: number;
  discount?: number;
  gstEnabled?: boolean;
  gstAmount?: number;
  total: number;
  amountPaid?: number;
  notes?: string;
  items: InvoiceItemInput[];
}

// Legacy admin invoices are "standalone" (weddingId: null). The Wedding
// Finance system (weddingWorkspace.service.ts, Sprint 7.x) already creates
// real wedding-linked Invoice rows in this same Postgres table — this
// service's list/get/update/delete only ever operate on standalone
// invoices, matching this route's historical scope exactly (it never knew
// wedding-linked invoices existed under Mongo) and keeping the Finance
// system's data untouched by an admin UI with no awareness of
// payments/reconciliation.
const STANDALONE: Prisma.InvoiceWhereInput = { weddingId: null };

export const invoiceService = {
  async list() {
    return invoiceRepository.findMany({ where: STANDALONE, orderBy: { createdAt: 'desc' } });
  },

  async getById(id: string) {
    const invoice = await invoiceRepository.findById(id);
    if (!invoice || invoice.weddingId) return null;
    return invoice;
  },

  // invoiceNumber is generated by the same function the Wedding Finance
  // system uses (weddingWorkspace.service.ts's generateInvoiceNumber, which
  // already counts against this shared table) rather than reimplementing
  // the old Mongo route's own (subtly different — a global, not
  // monthly-bucketed, counter) logic. Reusing it isn't just cleaner: since
  // invoiceNumber is @unique and both paths now write to the same table,
  // two independent numbering schemes could otherwise collide.
  async create(data: InvoiceCreateData) {
    // Same bounds check as update() — see its comment for why.
    if (data.amountPaid !== undefined && (data.amountPaid < 0 || data.amountPaid > data.total)) {
      throw new InvalidTransitionError(`amountPaid must be between 0 and the invoice total (${data.total})`);
    }

    return prisma.$transaction(async (tx) => {
      const invoiceNumber = await generateInvoiceNumber(tx);
      return invoiceRepository.create(
        {
          invoiceNumber,
          clientName: data.clientName,
          clientPhone: data.clientPhone,
          clientEmail: data.clientEmail,
          clientCity: data.clientCity,
          eventDate: data.eventDate,
          eventType: data.eventType,
          subtotal: data.subtotal,
          discount: data.discount,
          gstEnabled: data.gstEnabled,
          gstAmount: data.gstAmount,
          total: data.total,
          amountPaid: data.amountPaid,
          notes: data.notes,
          items: {
            create: data.items.map((i) => ({
              description: i.description,
              vendorName: i.vendorName,
              amount: i.amount,
              quantity: i.quantity,
            })),
          },
        },
        tx
      );
    });
  },

  // items, when provided, fully replace the invoice's existing InvoiceItem
  // rows — matches the admin edit form, which always resubmits the complete
  // item list, same pattern as Vendor packages (PR migrating vendors).
  // Replacing items before the scalar update (rather than after) so the
  // returned, include-d record reflects the final item list in one query.
  async update(id: string, data: Prisma.InvoiceUpdateInput, items?: InvoiceItemInput[]) {
    const existing = await invoiceRepository.findById(id);
    if (!existing || existing.weddingId) return null;

    // Standalone invoices have no automated payment collection (no Razorpay
    // payment-link route exists for them), so amountPaid is a manually
    // entered field by design — but it was previously accepted with zero
    // validation, and commandCenter/founderDashboard services read this
    // column directly into company-wide revenue figures. Bound it against
    // whichever total applies (the one being set in this same request, if
    // any, else the invoice's existing total) so a typo or fabricated value
    // can't corrupt those figures.
    const amountPaid = typeof data.amountPaid === 'number' ? data.amountPaid : undefined;
    if (amountPaid !== undefined) {
      const total = typeof data.total === 'number' ? data.total : existing.total;
      if (amountPaid < 0 || amountPaid > total) {
        throw new InvalidTransitionError(`amountPaid must be between 0 and the invoice total (${total})`);
      }
    }

    return prisma.$transaction(async (tx) => {
      if (items) {
        await tx.invoiceItem.deleteMany({ where: { invoiceId: id } });
        if (items.length) {
          await tx.invoiceItem.createMany({
            data: items.map((i) => ({
              invoiceId: id,
              description: i.description,
              vendorName: i.vendorName,
              amount: i.amount,
              quantity: i.quantity ?? 1,
            })),
          });
        }
      }
      return invoiceRepository.update(id, data, tx);
    });
  },

  async delete(id: string) {
    const existing = await invoiceRepository.findById(id);
    if (!existing || existing.weddingId) throw new NotFoundError('Invoice', id);
    return invoiceRepository.delete(id);
  },
};
